/**
 * Professional workspace icons using Heroicons
 * Simple, modern, black and white icons
 */
import {
  DocumentTextIcon,
  FolderIcon,
  BookOpenIcon,
  PencilSquareIcon,
  SparklesIcon,
  LightBulbIcon,
  RocketLaunchIcon,
  BeakerIcon,
  CodeBracketIcon,
  CpuChipIcon,
  CubeIcon,
  CommandLineIcon,
  ChartBarIcon,
  PresentationChartLineIcon,
  BriefcaseIcon,
  AcademicCapIcon,
  BuildingOfficeIcon,
  HomeIcon,
  GlobeAltIcon,
  MapIcon,
  PhotoIcon,
  FilmIcon,
  MusicalNoteIcon,
  PaintBrushIcon,
  SwatchIcon,
  ShoppingBagIcon,
  HeartIcon,
  StarIcon,
  BoltIcon,
  FireIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  WrenchScrewdriverIcon,
  CogIcon,
  ShieldCheckIcon,
  LockClosedIcon,
  KeyIcon,
  UserGroupIcon,
  ChatBubbleLeftRightIcon,
  EnvelopeIcon,
  PhoneIcon,
  VideoCameraIcon,
  MicrophoneIcon,
  SpeakerWaveIcon,
  CalculatorIcon,
  ClipboardDocumentListIcon,
  CalendarIcon,
  ClockIcon,
  BanknotesIcon,
  CreditCardIcon,
  ShoppingCartIcon,
  TruckIcon,
  BuildingStorefrontIcon,
  ScaleIcon,
  NewspaperIcon,
  BookmarkIcon,
  ArchiveBoxIcon,
  InboxIcon,
  FlagIcon,
  TrophyIcon,
  PuzzlePieceIcon,
  CubeTransparentIcon,
  CircleStackIcon,
  ServerIcon,
  SignalIcon,
  WifiIcon,
  DevicePhoneMobileIcon,
  ComputerDesktopIcon,
  TvIcon,
  PrinterIcon,
  CameraIcon,
  MagnifyingGlassIcon,
  AdjustmentsHorizontalIcon,
  Squares2X2Icon,
  QueueListIcon,
  TableCellsIcon,
  ListBulletIcon,
  ChartPieIcon,
  ArrowTrendingUpIcon,
  BanknotesIcon as CashIcon,
  ReceiptPercentIcon,
  TagIcon,
  TicketIcon,
  GiftIcon,
  BeakerIcon as LabIcon,
  MegaphoneIcon,
  LightBulbIcon as IdeaIcon,
  AcademicCapIcon as EducationIcon,
} from '@heroicons/react/24/outline';

export const WORKSPACE_ICONS = [
  { id: 'document', name: 'Document', Icon: DocumentTextIcon },
  { id: 'folder', name: 'Folder', Icon: FolderIcon },
  { id: 'book', name: 'Book', Icon: BookOpenIcon },
  { id: 'pencil', name: 'Write', Icon: PencilSquareIcon },
  { id: 'sparkles', name: 'Creative', Icon: SparklesIcon },
  { id: 'lightbulb', name: 'Ideas', Icon: LightBulbIcon },
  { id: 'rocket', name: 'Launch', Icon: RocketLaunchIcon },
  { id: 'beaker', name: 'Science', Icon: BeakerIcon },
  { id: 'code', name: 'Code', Icon: CodeBracketIcon },
  { id: 'cpu', name: 'Tech', Icon: CpuChipIcon },
  { id: 'cube', name: 'Product', Icon: CubeIcon },
  { id: 'terminal', name: 'Terminal', Icon: CommandLineIcon },
  { id: 'chart', name: 'Analytics', Icon: ChartBarIcon },
  { id: 'presentation', name: 'Presentation', Icon: PresentationChartLineIcon },
  { id: 'briefcase', name: 'Business', Icon: BriefcaseIcon },
  { id: 'academic', name: 'Education', Icon: AcademicCapIcon },
  { id: 'building', name: 'Office', Icon: BuildingOfficeIcon },
  { id: 'home', name: 'Home', Icon: HomeIcon },
  { id: 'globe', name: 'Global', Icon: GlobeAltIcon },
  { id: 'map', name: 'Map', Icon: MapIcon },
  { id: 'photo', name: 'Photo', Icon: PhotoIcon },
  { id: 'film', name: 'Video', Icon: FilmIcon },
  { id: 'music', name: 'Music', Icon: MusicalNoteIcon },
  { id: 'paint', name: 'Art', Icon: PaintBrushIcon },
  { id: 'swatch', name: 'Design', Icon: SwatchIcon },
  { id: 'shopping', name: 'Shopping', Icon: ShoppingBagIcon },
  { id: 'heart', name: 'Favorite', Icon: HeartIcon },
  { id: 'star', name: 'Star', Icon: StarIcon },
  { id: 'bolt', name: 'Energy', Icon: BoltIcon },
  { id: 'fire', name: 'Hot', Icon: FireIcon },
  { id: 'sun', name: 'Day', Icon: SunIcon },
  { id: 'moon', name: 'Night', Icon: MoonIcon },
  { id: 'cloud', name: 'Cloud', Icon: CloudIcon },
  { id: 'wrench', name: 'Tools', Icon: WrenchScrewdriverIcon },
  { id: 'cog', name: 'Settings', Icon: CogIcon },
  { id: 'shield', name: 'Security', Icon: ShieldCheckIcon },
  { id: 'lock', name: 'Private', Icon: LockClosedIcon },
  { id: 'key', name: 'Access', Icon: KeyIcon },
  { id: 'users', name: 'Team', Icon: UserGroupIcon },
  { id: 'chat', name: 'Chat', Icon: ChatBubbleLeftRightIcon },
  { id: 'email', name: 'Email', Icon: EnvelopeIcon },
  { id: 'phone', name: 'Phone', Icon: PhoneIcon },
  { id: 'video', name: 'Video Call', Icon: VideoCameraIcon },
  { id: 'microphone', name: 'Audio', Icon: MicrophoneIcon },
  { id: 'speaker', name: 'Sound', Icon: SpeakerWaveIcon },
  { id: 'calculator', name: 'Calculate', Icon: CalculatorIcon },
  { id: 'clipboard', name: 'Tasks', Icon: ClipboardDocumentListIcon },
  { id: 'calendar', name: 'Calendar', Icon: CalendarIcon },
  { id: 'clock', name: 'Time', Icon: ClockIcon },
  { id: 'banknotes', name: 'Finance', Icon: BanknotesIcon },
  { id: 'card', name: 'Payment', Icon: CreditCardIcon },
  { id: 'cart', name: 'Cart', Icon: ShoppingCartIcon },
  { id: 'truck', name: 'Delivery', Icon: TruckIcon },
  { id: 'store', name: 'Store', Icon: BuildingStorefrontIcon },
  { id: 'scale', name: 'Legal', Icon: ScaleIcon },
  { id: 'newspaper', name: 'News', Icon: NewspaperIcon },
  { id: 'bookmark', name: 'Saved', Icon: BookmarkIcon },
  { id: 'archive', name: 'Archive', Icon: ArchiveBoxIcon },
  { id: 'inbox', name: 'Inbox', Icon: InboxIcon },
  { id: 'flag', name: 'Flag', Icon: FlagIcon },
  { id: 'trophy', name: 'Achievement', Icon: TrophyIcon },
  { id: 'puzzle', name: 'Puzzle', Icon: PuzzlePieceIcon },
  { id: 'cube-transparent', name: '3D', Icon: CubeTransparentIcon },
  { id: 'database', name: 'Database', Icon: CircleStackIcon },
  { id: 'server', name: 'Server', Icon: ServerIcon },
  { id: 'signal', name: 'Signal', Icon: SignalIcon },
  { id: 'wifi', name: 'WiFi', Icon: WifiIcon },
  { id: 'mobile', name: 'Mobile', Icon: DevicePhoneMobileIcon },
  { id: 'desktop', name: 'Desktop', Icon: ComputerDesktopIcon },
  { id: 'tv', name: 'Display', Icon: TvIcon },
  { id: 'printer', name: 'Print', Icon: PrinterIcon },
  { id: 'camera', name: 'Camera', Icon: CameraIcon },
  { id: 'search', name: 'Search', Icon: MagnifyingGlassIcon },
  { id: 'adjustments', name: 'Adjust', Icon: AdjustmentsHorizontalIcon },
  { id: 'grid', name: 'Grid', Icon: Squares2X2Icon },
  { id: 'queue', name: 'Queue', Icon: QueueListIcon },
  { id: 'table', name: 'Table', Icon: TableCellsIcon },
  { id: 'list', name: 'List', Icon: ListBulletIcon },
  { id: 'pie-chart', name: 'Pie Chart', Icon: ChartPieIcon },
  { id: 'trending', name: 'Trending', Icon: ArrowTrendingUpIcon },
  { id: 'receipt', name: 'Receipt', Icon: ReceiptPercentIcon },
  { id: 'tag', name: 'Tag', Icon: TagIcon },
  { id: 'ticket', name: 'Ticket', Icon: TicketIcon },
  { id: 'gift', name: 'Gift', Icon: GiftIcon },
  { id: 'megaphone', name: 'Announce', Icon: MegaphoneIcon },
];

// Default icon
export const DEFAULT_ICON = 'document';

// Get icon component by ID
export const getIconById = (iconId) => {
  const icon = WORKSPACE_ICONS.find(i => i.id === iconId);
  return icon ? icon.Icon : DocumentTextIcon;
};
